export interface COAItem {
  code: string;
  name: string;
  category?: string; // e.g., Aset, Liabilitas, Ekuitas, Pendapatan, Beban
}

export interface TransactionItem {
  id: string;
  date: string;
  description: string;
  amount: number; // Positive for inflow, negative for outflow usually, or handled by type
  type: 'CR' | 'DB'; // CR (Credit/In), DB (Debit/Out) from Bank perspective
}

export interface JournalLine {
  accountCode: string;
  accountName: string;
  debit: number;
  credit: number;
}

export interface JournalEntry {
  id: string;
  date: string;
  description: string; // Original description
  narration: string; // Professional narration generated by AI
  lines: JournalLine[];
  isValid: boolean; // debit == credit
}

export enum AppState {
  LANDING = 'LANDING',
  APP = 'APP',
}

export enum ProcessingStatus {
  IDLE = 'IDLE',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR',
}
